name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: Kesin11/actions-timeline@v2
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: imas-moku-discord-event
          entrypoint: main.ts
          root: .
